// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Suggests a reasonable deadline for a task.
 *
 * - suggestDeadline - A function that suggests a deadline for a task.
 * - SuggestDeadlineInput - The input type for the suggestDeadline function.
 * - SuggestDeadlineOutput - The return type for the suggestDeadline function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const SuggestDeadlineInputSchema = z.object({
  taskDescription: z.string().describe('The description of the task.'),
});
export type SuggestDeadlineInput = z.infer<typeof SuggestDeadlineInputSchema>;

const SuggestDeadlineOutputSchema = z.object({
  suggestedDeadline: z.string().describe('The suggested deadline for the task in ISO 8601 format (YYYY-MM-DD).'),
  reasoning: z.string().describe('The reasoning behind the suggested deadline.'),
});
export type SuggestDeadlineOutput = z.infer<typeof SuggestDeadlineOutputSchema>;

export async function suggestDeadline(input: SuggestDeadlineInput): Promise<SuggestDeadlineOutput> {
  return suggestDeadlineFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestDeadlinePrompt',
  input: {
    schema: z.object({
      taskDescription: z.string().describe('The description of the task.'),
    }),
  },
  output: {
    schema: z.object({
      suggestedDeadline: z.string().describe('The suggested deadline for the task in ISO 8601 format (YYYY-MM-DD).'),
      reasoning: z.string().describe('The reasoning behind the suggested deadline.'),
    }),
  },
  prompt: `You are a helpful assistant that suggests reasonable deadlines for tasks.

  Given the following task description, suggest a reasonable deadline in ISO 8601 format (YYYY-MM-DD).
  Also, explain your reasoning for suggesting that deadline.

  Task Description: {{{taskDescription}}}
  `,
});

const suggestDeadlineFlow = ai.defineFlow<
  typeof SuggestDeadlineInputSchema,
  typeof SuggestDeadlineOutputSchema
>({
  name: 'suggestDeadlineFlow',
  inputSchema: SuggestDeadlineInputSchema,
  outputSchema: SuggestDeadlineOutputSchema,
},
async input => {
  const {output} = await prompt(input);
  return output!;
});
